version: 2
updates:
      
# Maintain dependencies for GitHub Wrokflows
  - package-ecosystem: "github/workflows"
    directory: "/"
    schedule:
      interval: "daily"
      
      
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      
  # Maintain dependencies for flutter
  - package-ecosystem: "flutter"
    directory: "/"
    schedule:
      interval: "daily"
      
  # Maintain dependencies for dart
  - package-ecosystem: "dart"
    directory: "/"
    schedule:
      interval: "daily"
