# version: 2
# updates:
#  on:
#  # Maintain dependencies for GitHub Actions
#   - package-ecosystem: "github-actions"
# # # Maintain dependencies for GitHub Wrokflows
# #   - package-ecosystem: "github/workflows"
#     directory: "/"
#     schedule:
#       interval: "daily"
      
      
#   # Maintain dependencies for npm
#   - package-ecosystem: "npm"
#     directory: "/"
#     schedule:
#       interval: "daily"

#   # Maintain dependencies for Composer
#   - package-ecosystem: "composer"
#     directory: "/"
#     schedule:
#       interval: "daily"
      
#   # Maintain dependencies for flutter
#   - package-ecosystem: "flutter"
#     directory: "/"
#     schedule:
#       interval: "daily"
      
#   # Maintain dependencies for dart
#   - package-ecosystem: "dart"
#     directory: "/"
#     schedule:
#       interval: "daily"

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
